algoritmo "Tabuada"

var
    n1:inteiro
inicio
      leia (n1)
      escreval (n1,"x1=", n1*1)
      escreval (n1,"x2=", n1*2)
      escreval (n1, "x", n1*3)
      escreval (n1, "x", n1*4)
      escreval (n1, "x", n1*5)
      escreval (n1, "x", n1*6)
      escreval (n1, "x", n1*7)
      escreval (n1, "x", n1*8)
      escreval (n1, "x", n1*9)
      escreval (n1, "x", n1*10)
      
fimalgoritmo
